### ISSUE TITLE
Two consecutive network failures occurred while submitting a batch of metrics

### ISSUE THREAD

**Issue by Mudlife318** [Pinkstink-Rust/Rust-Server-Metrics#10]
I keep receiving this error, but have no idea what could be causing it. It pops up in console about every 10 seconds or so
any ideas?

**Comment by features-not-bugs** [comment]
Sorry about the delay, although if you set the debug field to true in the config it will output the error from influx thats causing this.

**Comment by Kaysharp42** [comment]
Debug is set to true but i only get 
Two consecutive network failures occurred while submitting a batch of metrics
Two consecutive network failures occurred while submitting a batch of metrics

**Comment by Kaysharp42** [comment]
i printed the message error and its says Request timeout
```
Two consecutive network failures occurred while submitting a batch of metrics
Network error: Request timeout
```
