### ISSUE TITLE
Add support for Carbon server engine

### ISSUE THREAD

**Issue by ThePitereq** [Pinkstink-Rust/Rust-Server-Metrics#11]
Hello,
Unfortunatelly on Carbon I don't have Plugin Hook Times graph.
As I saw on code it's made on Oxide.Core library so it won't work on Carbon.
Can this be implemented as an feature, please? :)
![image](https://github.com/Pinkstink-Rust/Rust-Server-Metrics/assets/61802186/7afa0763-7cd3-4975-8474-c7c226b3fd40)

**Comment by features-not-bugs** [comment]
Sorry I have no plans to include this myself. Although anyone is welcome to add it in and make a PR
