### ISSUE TITLE
harmony don't load

### ISSUE THREAD

**Issue by Owned67** [Pinkstink-Rust/Rust-Server-Metrics#12]
[HarmonyLoader] Couldn't unload mod 'RustServerMetric': not loaded
[HarmonyLoader com.facepunch.rust_dedicated.RustServerMetric] Loading from F:/rust/RustDedicated_Data\..\HarmonyMods\RustServerMetric.dll
[HarmonyLoader com.facepunch.rust_dedicated.RustServerMetric] Failed to load harmony mod 'RustServerMetric.dll' from 'F:/rust/RustDedicated_Data\..\HarmonyMods'

I've other harmony extension and it load fine, only your search on other folder ^^

harmony mods is: F:\rust\HarmonyMods

ConsoleFilter, NoGiveNotice and WorldModifier load fine...

edit: ok so created the folder:
F:\rust\RustDedicated_Data\ServerMetrics\HarmonyMods

shutdown server, put the .dll and:
`[HarmonyLoader] Couldn't unload mod 'RustServerMetrics': not loaded
[HarmonyLoader com.facepunch.rust_dedicated.RustServerMetrics] Loading from F:/rust/RustDedicated_Data\..\HarmonyMods\RustServerMetrics.dll
[ServerMetrics]: The configuration seems to be missing or malformed. Defaults will be loaded.
[ServerMetrics]: Default database url detected in configuration, loading aborted
[ServerMetrics]: Default database name detected in configuration, loading aborted
[ServerMetrics]: Default server tag detected in configuration, loading aborted
[ServerMetrics]: Applying Startup Patches
[ServerMetrics]: Applied Startup Patch: ConsoleSystem_Internal_Patch
[ServerMetrics]: Applied Startup Patch: InvokeHandlerBase_DoTick_Patch
[ServerMetrics]: Applied Startup Patch: ObjectWorkQueue_RunJob_Patch`

Config file are located on F:\rust\HarmonyMods_Data\ServerMetrics folder.

it's good?

Thanks

**Comment by GhilleAU** [comment]
If still an issue re-open
