### ISSUE TITLE
Player avarages aren't working properly in Grafana v10

### ISSUE THREAD

**Issue by farkas1121** [Pinkstink-Rust/Rust-Server-Metrics#14]
Player Avarages where all the steam IDs are selected by default (Player FPS, Player Latency, Player Packet Loss, Player Memory) do not load when using grafana v10, that was released recently.
I'm not sure whether there is a proper fix, but I think the readme should at least be update to show Grafana v9.x instead of Grafana v9+

**Comment by JackoPlane** [comment]
Did you ever find a solution for this?

**Comment by MONaH-Rasta** [comment]
Works as expected for me (Grafana v10.2.2)

**Comment by JackoPlane** [comment]
Are you using Carbon or Oxide?

**Comment by MONaH-Rasta** [comment]
@JackoPlane, I'm using Oxide
