### ISSUE TITLE
Error with Player FPS and Memory after Aug 4 2022 Update

### ISSUE THREAD

**Issue by shady14u** [Pinkstink-Rust/Rust-Server-Metrics#2]
After Aug 4 2022 Update Player FPS locked at 71 SEXT and memory is 0

**Comment by djzoneporro** [comment]
if i was going crazy and i updated grafana to 9.0 and it still doesn't work, maybe it's a harmony bug, they will have to find a solution and update it.

**Comment by features-not-bugs** [comment]
All fixed with https://github.com/Pinkstink-Rust/Rust-Server-Metrics/releases/tag/release-v1.1.8
