### ISSUE TITLE
No longer getting invoke times.

### ISSUE THREAD

**Issue by Mike6FO** [Pinkstink-Rust/Rust-Server-Metrics#22]
Since the June 6th update, invoke times are no longer being reported.

![noinvoke](https://github.com/Pinkstink-Rust/Rust-Server-Metrics/assets/168779341/4a350395-525f-42f3-8c7d-b3a3b808bea6)

**Comment by GhilleAU** [comment]
Fixed, didn't see this issue until now.

**Comment by Mike6FO** [comment]
Thank you!
