### ISSUE TITLE
Tracking memory consumption by method.

### ISSUE THREAD

**Issue by SkiTee3000** [Pinkstink-Rust/Rust-Server-Metrics#23]
Are there plans to implement memory consumption tracking with MonoProfiler for example, as well as code execution time tracking by methods with the same MonoProfiler?

**Comment by IvMisticos** [comment]
The profiler API could be used indeed for such purposes (tracking CPU time and memory consumption by method), but RSM is pretty far from being just that / about that. Therefore the suggestion sounds rather irrelevant. In my opinion it would be the wrong tool for the job you want done.
