### ISSUE TITLE
1.5.1 no client data and seems to break various other things.

### ISSUE THREAD

**Issue by Mike6FO** [Pinkstink-Rust/Rust-Server-Metrics#24]
Loaded 1.5.1 on two different servers.  Both servers no longer reporting client details like player latency, player fps, etc.

Also, players are not able to interact with vehicles and wounded screen never exits.  Timer keeps counting down in negative numbers.

Steps done:
Downgraded back to 1.5.0 and issues resolved.
Re-updated to 1.5.1 and issues returned.

**Comment by GhilleAU** [comment]
Fixed, apologies for the Inconvenience.

**Comment by Mike6FO** [comment]
Thank you!  :)
