### ISSUE TITLE
Question: How to Display Player Names in Table for Servers

### ISSUE THREAD

**Issue by jchambo** [Pinkstink-Rust/Rust-Server-Metrics#26]
Hey there - is it possible to display "Player Names" (not Steam64 ID's) in a Table Visualization in Grafana? If so, any idea how to build the Query / Panel for it?

I'd like to basically create a Table view like this:

| PLAYER NAME  | SERVER | STATUS |
| ------------- | ------------- | ------------- |
| PlayerName1  | 2x Monthly  | Connected |
| PlayerName2  | 2x Trio  | Joining |
| PlayerName3  | 2x Monthly  | Joining |
| PlayerName4  | 2x Trio| Queued |

Something along those lines. I'm just not the greatest at digging into what data is available in InfluxDB, so wanted to pick your brain if Player Names are even being gathered at all with RSM?

I have low pop servers at the moment, so this information is valuable for my use case, but probably not for high pop servers.

**Comment by GhilleAU** [comment]
Well to start, **anything's possible**!

Player names arent currently collected by RSM though feel free to create a fork and incorporate it yourself.
