### ISSUE TITLE
After Today's Mandatory Facepunch Update, RustServerMetrics.dll needs an Update

### ISSUE THREAD

**Issue by jchambo** [Pinkstink-Rust/Rust-Server-Metrics#27]
Hey there - RSM currently doesn't allow players to load into servers where it is running after today's mandatory Facepunch update.

If players attempt to connect they see the following:

![image](https://github.com/Pinkstink-Rust/Rust-Server-Metrics/assets/26009241/8ca31bd4-2ca7-4d26-a4ed-a546d1638648)

![image](https://github.com/Pinkstink-Rust/Rust-Server-Metrics/assets/26009241/66e55885-cc2b-4820-b59c-59c56a50546e)

Removing **RustServerMetrics.dll** from **/home/container/HarmonyMods** and rebooting the server fixes the issue.

**Comment by GhilleAU** [comment]
this is not good

**Comment by jchambo** [comment]
Yup, Facepunch broke a lot of stuff today with their Mandatory update....
