### ISSUE TITLE
Problems running this on Carbon.

### ISSUE THREAD

**Issue by Zand3rsCode** [Pinkstink-Rust/Rust-Server-Metrics#31]
Hello.

When i install this on Carbon noone can wake up when they log in. Confirmed working in Oxide with same configuration!
Is Carbon supported?

**Comment by IvMisticos** [comment]
Hello, this mod does not really depend on the modding framework - at most integrates with Oxide. It looks like Carbon run their own fork as well - I would guess they break compatibility with vanilla in some way.
