### ISSUE TITLE
If i am using carbon, the  RustServerMetrics.dll harmony mod keeps my server in infinite loading and does not load

### ISSUE THREAD

**Issue by BittuCNGT** [Pinkstink-Rust/Rust-Server-Metrics#32]
If i am using carbon, the  RustServerMetrics.dll harmony mod keeps my server in infinite loading and does not load but on removing the mod from the harmony folder in carbon directory server loads normally, when not loading it creates the HarmonyMods_Data and the config file normally but the server does not load.
i didnt had the issue when on oxide.
any help?

**Comment by BittuCNGT** [comment]
so should i contact carbon people to make it work like them adding support ?

**Comment by MONaH-Rasta** [comment]
You can try. As far as I know, the owner of this repo doesn't mind if someone creates pull requests.
https://github.com/Pinkstink-Rust/Rust-Server-Metrics/issues/11

**Comment by BittuCNGT** [comment]
will ask them if they can do anything because this helps me dealing with ddos attacks on my server and also checking what is causing server lag

**Comment by Jexs** [comment]
As Monah said, Carbon isn't currently supported and no current plans to add support from the maintainers. PRs always welcome, though.

Closing for now.
