### ISSUE TITLE
HTTP Errors

### ISSUE THREAD

**Issue by BippyMiester** [Pinkstink-Rust/Rust-Server-Metrics#7]
Not sure why I keep getting this spammed in my console.... But it started happening recently and IDK how to fix it.

5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request

**Comment by features-not-bugs** [comment]
Enable debug logging in the configuration file and reload the config, it will begin spitting out the raw response back from influxdb which should give you the error reason. 

Ensure you have followed step 2 in the readme as that's the most common reason for influxdb 400 responses with this mod.

**Comment by JDsWebService** [comment]
5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587658267': invalid field format dropped=0"}
5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587664272': invalid field format dropped=0"}
5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587670287': invalid field format dropped=0"}
5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587676296': invalid field format dropped=0"}
4 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587681327': invalid field format dropped=0"}
5 subsequent HTTP errors occurred in the last 5 seconds
A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
{"error":"partial write: unable to parse 'oxide_plugins,server=9Lives-Hardcore,plugin=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\" hookTime=0 1676587687338': invalid field format dropped=0"}

**Comment by JDsWebService** [comment]
I don't think that this is a database issue that step 2 could solve? Maybe? I did step 2 in the readme. So I'm not sure where to go from here. Any ideas? Seems like the issue has to do with a plugin? But i don't have a plugin name of ""s/\u003eqK~?tlV[L gOu"XGkQdI1'" so idk what that is...

**Comment by JDsWebService** [comment]
@features-not-bugs Any update on this? Trying to get this to work still and I'm running into the same issues.

**Comment by RocketMyrr** [comment]
Had the same problem. i had to write in a scrubber for the plugin name. that took out any weird symbols so the script could parse properly

**Comment by JDsWebService** [comment]
> Had the same problem. i had to write in a scrubber for the plugin name. that took out any weird symbols so the script could parse properly

Ok so how do I go about doing this since nobody is commenting from the contributors on how to fix this issue?

**Comment by features-not-bugs** [comment]
Do you use the RustEdit oxide extension by chance?

**Comment by JDsWebService** [comment]
I do yes. Its updated to the latest version

**Comment by features-not-bugs** [comment]
Ok, I presume it's because the Author of the extension is loading in an obfuscated plugin as an internal oxide plugin which is causing the behaviour you're seeing, I'll add some filtering to this mod to automatically exclude any plugins with an invalid name.

**Comment by JDsWebService** [comment]
That sounds like something KillYou would do. He's really been updating his security lately due to his plugins and code being stolen. So this sounds exactly what he's doing. One of his plugins actually downloads a custom dll file that handles some of his UI stuff. So it could also be that DLL file as well. A link is below to what I'm talking about.

https://chaoscode.io/resources/chaos.321/

and the DLL can be found here: https://chaoscode.io/oxide/Oxide.Ext.Chaos.dll

Both of them (RustEdit DLL and the ChaosDLL are made by KillYou)

**Comment by features-not-bugs** [comment]
Just waiting on CI/CD to build this release out, once it's done (5 mins or so) you can download it from here: https://github.com/Pinkstink-Rust/Rust-Server-Metrics/releases/tag/release-v1.4.2

Give that a go and let me know if it works.

**Comment by features-not-bugs** [comment]
Use this release instead actually, https://github.com/Pinkstink-Rust/Rust-Server-Metrics/releases/tag/release-v1.4.3

Just added testing for invalid starting characters also.

**Comment by JDsWebService** [comment]
Kk. I saw that you pushed a new one. I'll use that one instead and report back to you.

**Comment by JDsWebService** [comment]
Still getting this error:

(03:19:10) | 4 subsequent HTTP errors occurred in the last 5 seconds
(03:19:10) | A HTTP error occurred while submitting batch of metrics: HTTP/1.1 400 Bad Request
(03:19:10) | {"error":"partial write: unable to parse 'oxide_plugins,server=pve-3x,plugin=\"s/\u003eqK~?tlV[L gOu\\\"XGkQdI1'\" hookTime=0 1677053950659': invalid field format dropped=0"}

**Comment by RocketMyrr** [comment]
It's not pulling all the symbols out of the name. I just removed it with a regex scrub so would only leave alpha/numeric no symbols at all cause wasn't sure what was causing the error. I can do a pull request if want

**Comment by features-not-bugs** [comment]
Yeah I was trying to avoid the extra cost of Regex, but I've just released an update that will strip anything that's not alphanumeric from the plugin name.

Give this one a go and it should work.
https://github.com/Pinkstink-Rust/Rust-Server-Metrics/releases/tag/release-v1.4.4

**Comment by JDsWebService** [comment]
Thanks for your hard work!

**Comment by features-not-bugs** [comment]
No worries, enjoy

**Comment by JDsWebService** [comment]
Welp, I guess i spoke too soon. Using the most updated version from the releases, and its doing it again... I do have a few new plugins and harmony mods as well.

Error:
`{"error":"partial write: unable to parse 'invoke_execution,server=artemis,behaviour=\"s/\u003eqK~?tlV[L gOu\"XGkQdI1'\",method=\"‎‌‫‪‍⁭⁪⁮⁬‭‭⁯⁪‭‪‬⁬‫⁬‏‎‌‏⁫⁪‭‭​⁬⁬⁬⁪‏​‎‏‍⁬⁭‍\" duration=0.0023 1677293682221': invalid field format dropped=0"}`

These are the list of plugins installed:

```
(21:56:24) | Listing 148 plugins:
  01 "AFK" (1.1.5) by Wulf/lukespragg (0.01s) - AFK.cs
  02 "Admin Logger" (2.4.0) by AK (0.09s) - AdminLogger.cs
  03 "AdminMenu" (2.0.10) by k1lly0u (9.04s) - AdminMenu.cs
  04 "Admin No Loot" (0.1.3) by Dana (0.03s) - AdminNoLoot.cs
  05 "Admin Radar" (5.1.9) by nivex (15.75s) - AdminRadar.cs
  06 "AdvancedAlerts" (1.3.0) by ProCelle (4.23s) - AdvancedAlerts.cs
  07 "Alias System" (2.1.3) by LaserHydra (0.00s) - AliasSystem.cs
  08 "AlphaLoot" (3.1.20) by k1lly0u (14.93s) - AlphaLoot.cs
  09 "Always Bonus" (1.1.1) by Tryhard (0.00s) - AlwaysBonus.cs
  10 "Anti Ladder and Twig" (1.3.1) by kaucsenta (0.00s) - AntiLadderandTwig.cs
  11 "Anti Spam" (2.0.2) by MON@H (0.02s) - AntiSpam.cs
  12 "Arkan" (1.0.19) by Antidote (0.34s) - Arkan.cs
  13 "ArmoredTrain" (1.2.4) by Adem (9.52s) - ArmoredTrain.cs
  14 "AutoBaseUpgrade" (1.1.0) by CASHR#6906 (0.10s) - AutoBaseUpgrade.cs
  15 "Auto CCTV Stations" (1.1.0) by Khan (0.04s) - AutoCCTVStations.cs
  16 "Auto Demo Record Lite" (1.0.82) by Pho3niX90 (0.00s) - AutoDemoRecordLite.cs
  17 "Auto Lock" (2.4.4) by birthdates (0.01s) - AutoLock.cs
  18 "Auto Stash Traps" (0.2.9) by Dana (0.26s) - AutoStashTraps.cs
  19 "Automatic Authorization" (1.3.3) by k1lly0u/Arainrr (1.25s) - AutomaticAuthorization.cs
  20 "BGrade" (1.1.3) by Ryan / Rustoria.co (0.03s) - BGrade.cs
  21 "Backpacks" (3.10.0) by WhiteThunder (0.26s) - Backpacks.cs
  22 "Better Chat" (5.2.12) by LaserHydra (0.00s) - BetterChat.cs
  23 "Better Chat Mute" (1.2.1) by LaserHydra (0.04s) - BetterChatMute.cs
  24 "Better Chat Filter" (1.6.8) by NooBlet (0.00s) - BetterChatFilter.cs
  25 "Better Say" (3.0.1) by LaserHydra (0.01s) - BetterSay.cs
  26 "Blueprint Manager" (2.0.6) by Whispers88 (0.42s) - BlueprintManager.cs
  27 "BotReSpawn" (1.1.8) by Steenamaroo (9.67s) - BotReSpawn.cs
  28 "Bradley" (1.3.5) by Ts3Hosting (3.05s) - Bradley.cs
  29 "Building Workbench" (1.3.2) by MJSU (3.90s) - BuildingWorkbench.cs
  30 "Bypass Queue" (1.0.4) by Orange (0.00s) - BypassQueue.cs
  31 "CargoPlaneCrash" (1.1.9) by Fruster (2.19s) - CargoPlaneCrash.cs
  32 "Cases" (1.1.2) by Mevent (3.05s) - Cases.cs
  33 "Chainsaw Options" (1.1.1) by Arainrr (0.11s) - ChainsawOptions.cs
  34 "ChaosExtensionDownloader" (0.1.0) by k1lly0u (0.00s) - ChaosExtensionDownloader.cs
  35 "Clans" (3.0.32) by k1lly0u (0.36s) - Clans.cs
  36 "Clear Night" (2.3.6) by Clearshot (10.87s) - ClearNight.cs
  37 "Convoy" (2.2.0) by Adem (0.26s) - Convoy.cs
  38 "Copy Paste" (4.1.33) by misticos (0.16s) - CopyPaste.cs
  39 "CustomLoot" (1.1.9) by Steenamaroo (4.41s) - CustomLoot.cs
  40 "Custom Map Name" (1.0.0) by Billy Joe (0.00s) - CustomMapName.cs
  41 "Death Notes" (6.3.8) by LaserHydra (0.82s) - DeathNotes.cs
  42 "DiscordClans" (0.1.2) by k1lly0u (0.02s) - DiscordClans.cs
  43 "Discord Logger" (2.0.11) by MON@H (0.27s) - DiscordLogger.cs
  44 "DiscordMessages" (2.1.8) by Slut (0.07s) - DiscordMessages.cs
  45 "Discord Presence" (2.0.4) by MJSU (0.44s) - DiscordPresence.cs
  46 "DiscordRewards" (0.2.4) by k1lly0u (0.47s) - DiscordRewards.cs
  47 "Discord Server Stats" (2.1.0) by MJSU (0.44s) - DiscordServerStats.cs
  48 "EasyVote" (2.0.45) by Exel80 (0.01s) - EasyVote.cs
  49 "Entity Limit" (2.1.3) by Orange/The Friendly Chap (3.04s) - EntityLimit.cs
  50 "Entity Owner" (3.4.1) by Calytic (0.09s) - EntityOwner.cs
  51 "Eternal Plants" (1.0.1) by 0x89A (0.00s) - EternalPlants.cs
  52 "Everlight" (3.4.17) by Wulf/lukespragg/Arainrr (0.69s) - Everlight.cs
  53 "Excavator Lock" (0.4.16) by Lorenzo (0.20s) - ExcavatorLock.cs
  54 "Freeze" (3.0.3) by Wulf (12.74s) - Freeze.cs
  55 "FurnaceSorter" (1.3.4) by PsychoTea (1.69s) - FurnaceSorter.cs
  56 "GUIAnnouncements" (2.0.3) by JoeSheep (3.95s) - GUIAnnouncements.cs
  57 "Gather Manager" (2.2.78) by Mughisi (0.37s) - GatherManager.cs
  58 "Give" (3.4.1) by Wulf (0.05s) - Give.cs
  59 "Godmode" (4.2.12) by Wulf/lukespragg/Arainrr (1.06s) - Godmode.cs
  60 "HitIcon" (2.0.0) by FastBurst (0.12s) - HitIcon.cs
  61 "HomesGUI" (1.4.22) by PsychoTea (4.30s) - HomesGUI.cs
  62 "Image Library" (2.0.60) by Absolut & K1lly0u (0.42s) - ImageLibrary.cs
  63 "Godmode Indicator" (2.1.2) by 2CHEVSKII (0.01s) - GodmodeIndicator.cs
  64 "ImprovedDoorClosers" (1.0.1) by Death (0.30s) - ImprovedDoorClosers.cs
  65 "InfoHudBar" (1.0.5) by CASHR#6906 (0.46s) - InfoHudBar.cs
  66 "InstantAirdrop" (1.0.2) by Steenamaroo (0.42s) - InstantAirdrop.cs
  67 "Instant Barrel" (1.1.5) by Tryhard (0.18s) - InstantBarrel.cs
  68 "Instant Craft" (2.2.1) by Vlad-0003 / Orange / rostov114 (0.00s) - InstantCraft.cs
  69 "Inventory Cleaner" (2.1.1) by Joao Pster (0.03s) - InventoryCleaner.cs
  70 "Inventory Viewer" (4.0.5) by Whispers88 (0.04s) - InventoryViewer.cs
  71 "Invite Command" (1.0.0) by Farkas (0.01s) - Invite.cs
  72 "Keywords" (1.3.1) by Wulf (0.04s) - Keywords.cs
  73 "Kits" (1.2.3) by Mevent (9.12s) - Kits.cs
  74 "Loading Messages" (1.0.9) by CosaNostra/Def/klauz24 (0.14s) - LoadingMessages.cs
  75 "Lock Master" (1.1.8) by FastBurst (4.86s) - LockMaster.cs
  76 "Loot Bouncer" (1.0.9) by Sorrow/Arainrr (0.52s) - LootBouncer.cs
  77 "Loot Defender" (2.1.1) by Author Egor Blagov, Maintainer nivex (4.98s) - LootDefender.cs
  78 "MLRS Respawner" (1.0.0) by WhiteThunder (0.00s) - MLRSRespawner.cs
  79 "MeteorEvent" (1.2.11) by ThePitereq (4.13s) - MeteorEvent.cs
  80 "Mini-Copter Options" (2.4.0) by Pho3niX90 (1.02s) - MiniCopterOptions.cs
  81 "Minicopter Seating" (1.1.6) by Bazz3l (0.27s) - MinicopterSeating.cs
  82 "Monuments Recycler" (0.2.6) by Dana (0.26s) - MonumentsRecycler.cs
  83 "My Mini Copter" (0.4.9) by RFC1920 (9.45s) - MyMiniCopter.cs
  84 "NPCKits" (1.1.6) by Steenamaroo (6.86s) - NPCKits.cs
  85 "NightVision" (2.4.1) by Clearshot (1.52s) - NightVision.cs
  86 "No Durability" (2.2.5) by Wulf/lukespragg/Arainrr (0.03s) - NoDurability.cs
  87 "No Escape" (2.1.35) by Calytic (1.90s) - NoEscape.cs
  88 "No Give Notices" (0.3.0) by Wulf (0.00s) - NoGiveNotices.cs
  89 "NpcSpawn" (2.4.8) by KpucTaJl (4.22s) - NpcSpawn.cs
  90 "Payback" (1.9.8) by 1928Tommygun (1.19s) - Payback.cs
  91 "Perfect Repair" (1.1.0) by Orange (0.00s) - PerfectRepair.cs
  92 "Personal Heli" (1.1.8) by Egor Blagov (4.96s) - PersonalHeli.cs
  93 "PersonalRecycler" (1.0.6) by imthenewguy (0.30s) - PersonalRecycler.cs
  94 "Placeholder API" (2.2.1) by misticos (0.12s) - PlaceholderAPI.cs
  95 "Planterbox Defender" (2.1.0) by kaucsenta (0.00s) - PlanterboxDefender.cs
  96 "Player Rankings" (3.0.3) by Ankawi (0.02s) - PlayerRankings.cs
  97 "PlayerRanks" (2.2.2) by Steenamaroo (1.89s) - PlayerRanks.cs
  98 "Playtime Tracker" (0.2.2) by k1lly0u (0.90s) - PlaytimeTracker.cs
  99 "PowerlessNeon" (1.1.0) by MNGO (0.27s) - PowerlessNeon.cs
  100 "PreventLooting" (1.12.1) by CaseMan (0.03s) - PreventLooting.cs
  101 "PrivateMessages" (1.1.11) by MisterPixie (0.00s) - PrivateMessages.cs
  102 "Quick Smelt" (5.1.5) by misticos (2.11s) - QuickSmelt.cs
  103 "RTM" (1.3.1) by AhigaO#4485 (0.06s) - RTM.cs
  104 "Raidable Bases" (2.6.7) by nivex (0.04s) - RaidableBases.cs
  105 "Random Respawner" (1.2.4) by Egor Blagov/Arainrr (0.01s) - RandomRespawner.cs
  106 "Remover Tool" (4.3.35) by Reneb/Fuji/Arainrr (0.03s) - RemoverTool.cs
  107 "Restore Upon Death" (0.5.0) by k1lly0u (0.11s) - RestoreUponDeath.cs
  108 "RustRewards" (3.1.0) by Steenamaroo (5.82s) - RustRewards.cs
  109 "SAMSiteAuth" (2.4.3) by haggbart (0.00s) - SAMSiteAuth.cs
  110 "SQLStats" (1.0.5) by Visagalis (0.09s) - SQLStats.cs
  111 "Scientist Names" (1.2.2) by Ultra (1.95s) - ScientistNames.cs
  112 "Server Rewards" (0.4.74) by k1lly0u (2.61s) - ServerRewards.cs
  113 "Sign Artist" (1.4.0) by Whispers88 (0.00s) - SignArtist.cs
  114 "Signal Cooldown" (1.0.32) by Vliek (0.01s) - SignalCooldown.cs
  115 "Simple Kill Feed" (2.1.2) by Krungh Crow (0.06s) - SimpleKillFeed.cs
  116 "Skill Tree" (1.3.0) by imthenewguy (2.54s) - SkillTree.cs
  117 "SkillTreeItems" (1.0.0) by imthenewguy (0.57s) - SkillTreeItems.cs
  118 "SkinBox" (2.1.21) by k1lly0u (0.20s) - SkinBox.cs
  119 "Smart Chat Bot" (2.0.13) by Iv Misticos (0.11s) - SmartChatBot.cs
  120 "SmartWarningsLite" (1.1.1) by FAKENINJA (0.95s) - SmartWarningsLite.cs
  121 "Sputnik" (1.1.1) by Adem (2.11s) - Sputnik.cs
  122 "Stack Size Controller" (4.1.1) by AnExiledDev (1.58s) - StackSizeController.cs
  123 "SubmersiblePump" (1.0.5) by ThePitereq (0.17s) - SubmersiblePump.cs
  124 "SuicideKill" (1.0.1) by Ankawi (0.00s) - SuicideKill.cs
  125 "Supply Signal Limit" (0.0.2) by bsdinis (2.46s) - SupplySignalLimit.cs
  126 "Tebex Donate" (1.7.0) by Tebex (2.22s) - TebexDonate.cs
  127 "TeleportGUI" (1.7.25) by PsychoTea (1.43s) - TeleportGUI.cs
  128 "Teleport Marker" (1.0.6) by Talha (0.18s) - TeleportMarker.cs
  129 "TimeOfDay" (2.3.4) by FuJiCuRa (0.00s) - TimeOfDay.cs
  130 "Timed Permissions" (1.6.0) by LaserHydra (0.01s) - TimedPermissions.cs
  131 "Trade" (1.2.43) by Calytic (0.01s) - Trade.cs
  132 "TruePVE" (2.0.8) by nivex (30.98s) - TruePVE.cs
  133 "UberTool" (1.4.26) by FuJiCuRa (0.09s) - UberTool.cs
  134 "Unburnable Meat" (1.0.1) by S642667 (0.00s) - UnburnableMeat.cs
  135 "UpdateChecker" (3.1.0) by tofurahie#4144 (0.04s) - UpdateChecker.cs
  136 "Vanish" (1.6.8) by Whispers88 (0.13s) - Vanish.cs
  137 "Vending Loot Drop" (1.0.6) by Bazz3l (0.18s) - VendingLootDrop.cs
  138 "Vending Machine Timeout" (1.0.15) by 0x89A (0.00s) - VendingMachineTimeout.cs
  139 "Vendor Rotate Protection" (1.1.3) by nuchacho/Arainrr (0.00s) - VendorRotateProtection.cs
  140 "WPVipRanks" (1.1.4) by David (0.01s) - WPVipRanks.cs
  141 "Water Catcher Boost" (1.0.3) by Substrata (0.00s) - WaterCatcherBoost.cs
  142 "Weather Events" (1.4.0) by OuTSMoKE, Rick (0.00s) - WeatherEvents.cs
  143 "WelcomePanel" (3.0.7) by David (4.74s) - WelcomePanel.cs
  144 "Whitelist" (3.3.0) by Wulf/lukespragg (0.03s) - Whitelist.cs
  145 "Whoa Boy" (1.1.0) by Clearshot (0.00s) - WhoaBoy.cs
  146 "ZombieHorde" (0.6.8) by k1lly0u (7.76s) - ZombieHorde.cs
  147 "Zone Manager" (3.0.23) by k1lly0u (5.85s) - ZoneManager.cs
  148 "Zone Manager Auto Zones" (1.3.6) by FastBurst (0.53s) - ZoneManagerAutoZones.cs
```

And the list of harmony mods are here: https://prnt.sc/4ld--_T5S6Wn

@features-not-bugs

**Comment by features-not-bugs** [comment]
I've requested that K1lly0u updates his obfuscation methods to only set alphanumeric names for Types, Methods and Plugin names. This should resolve the issue entirely.

While I could add name filtering to all tags sent to influx, the performance penalty would be quite great in doing so. I'm hoping that K1lly0u is happy to co-operate, I'll let you know when I hear back.

**Comment by JDsWebService** [comment]
thanks for reopening the issue for me. I'm hopeful that killyou will update this and push some type of update to his stuff so this isn't quite as broken. But like i said in my previous message, its only happening once every hour, which is something i can deal with. Prior to that it was every 5 seconds. So progress is better then no progress. Again thanks for working with me on this one.

Another quick note, some of the "panels" on the grafana dashboard take a super long time to pull any data. Is this an issue with there being no data to pull from the influxdb and thats why its stuck on the spinning circle of death in the top right hand corner of the panel? or is it because the grafana/influxdb needs more processing power? Have you ever run into this issue?

**Comment by SturdyStubs** [comment]
{"error":"partial write: unable to parse 'framerate,server=VanityCarbonClient instant=1,average=NaN 1705117800172': invalid number\nunable to parse 'frametime,server=VanityCarbonClient instant=3236.638,average=Infinity 1705117800172': invalid boolean dropped=0"}

Getting HTTP 400 errors on Carbon.

**Comment by features-not-bugs** [comment]
> 1705117800172

This is a different problem. This mod doesn't support carbon. It only support Vanilla and OxideMod servers.

**Comment by SturdyStubs** [comment]
Carbon has added support and many tables do show up.
![image](https://github.com/Pinkstink-Rust/Rust-Server-Metrics/assets/26588453/836e9aa7-b72f-4c5c-a342-99a3eb9d8086)

Player FPS, Memory, Latency, Packet Loss are the only ones down besides plugin hook times which I understand aren't necessarily possible with their dynamic hook system.

**Comment by features-not-bugs** [comment]
If Carbon has added support for this then they will need to continue supporting it.

I do and will not support using this with a Carbon modded server.

**Comment by features-not-bugs** [comment]
You're errors do look to be only and issue that would happen in the first frame as NaN and Infinity values have been sent. Once the Math can complete correctly after the first second it should be fine.
